/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.5.0
 * Generated at: 2026-04-08T22:20:36.395271+00:00
 * Generator: none
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */

import { invoke } from '@tauri-apps/api/core';
import * as types from './types';

export async function createMeal(params: types.CreateMealParams): Promise<types.Meal> {
  return invoke('create_meal', params);
}


export async function getMeal(params: types.GetMealParams): Promise<types.Meal | null> {
  return invoke('get_meal', params);
}



export async function listMeals(): Promise<types.Meal[]> {
  return invoke('list_meals');
}


export async function updateMeal(params: types.UpdateMealParams): Promise<types.Meal> {
  return invoke('update_meal', params);
}


export async function deleteMeal(params: types.DeleteMealParams): Promise<boolean> {
  return invoke('delete_meal', params);
}


export async function createMealItem(params: types.CreateMealItemParams): Promise<types.MealItem> {
  return invoke('create_meal_item', params);
}


export async function getMealItem(params: types.GetMealItemParams): Promise<types.MealItem | null> {
  return invoke('get_meal_item', params);
}


export async function listMealItemsByMeal(params: types.ListMealItemsByMealParams): Promise<types.MealItem[]> {
  return invoke('list_meal_items_by_meal', params);
}


export async function updateMealItem(params: types.UpdateMealItemParams): Promise<types.MealItem> {
  return invoke('update_meal_item', params);
}


export async function deleteMealItem(params: types.DeleteMealItemParams): Promise<boolean> {
  return invoke('delete_meal_item', params);
}


export async function listMealsByDateRange(params: types.ListMealsByDateRangeParams): Promise<types.Meal[]> {
  return invoke('list_meals_by_date_range', params);
}


export async function buildNlog(params: types.BuildNlogParams): Promise<string> {
  return invoke('build_nlog', params);
}


export async function createFood(params: types.CreateFoodParams): Promise<types.Food> {
  return invoke('create_food', params);
}


export async function getFood(params: types.GetFoodParams): Promise<types.Food | null> {
  return invoke('get_food', params);
}



export async function listFoods(): Promise<types.Food[]> {
  return invoke('list_foods');
}


export async function updateFood(params: types.UpdateFoodParams): Promise<types.Food> {
  return invoke('update_food', params);
}


export async function deleteFood(params: types.DeleteFoodParams): Promise<boolean> {
  return invoke('delete_food', params);
}


export async function createServing(params: types.CreateServingParams): Promise<types.Serving> {
  return invoke('create_serving', params);
}


export async function getServing(params: types.GetServingParams): Promise<types.Serving | null> {
  return invoke('get_serving', params);
}


export async function listServingsByFood(params: types.ListServingsByFoodParams): Promise<types.Serving[]> {
  return invoke('list_servings_by_food', params);
}


export async function updateServing(params: types.UpdateServingParams): Promise<types.Serving> {
  return invoke('update_serving', params);
}


export async function deleteServing(params: types.DeleteServingParams): Promise<boolean> {
  return invoke('delete_serving', params);
}


export async function createNutritionFacts(params: types.CreateNutritionFactsParams): Promise<types.NutritionFacts> {
  return invoke('create_nutrition_facts', params);
}


export async function getNutritionFacts(params: types.GetNutritionFactsParams): Promise<types.NutritionFacts | null> {
  return invoke('get_nutrition_facts', params);
}



export async function listNutritionFacts(): Promise<types.NutritionFacts[]> {
  return invoke('list_nutrition_facts');
}


export async function updateNutritionFacts(params: types.UpdateNutritionFactsParams): Promise<types.NutritionFacts> {
  return invoke('update_nutrition_facts', params);
}


export async function deleteNutritionFacts(params: types.DeleteNutritionFactsParams): Promise<boolean> {
  return invoke('delete_nutrition_facts', params);
}



export async function getNetworkConfig(): Promise<types.NetworkConfig> {
  return invoke('get_network_config');
}



export async function getDbPath(): Promise<string> {
  return invoke('get_db_path');
}



export async function getDatabaseSession(): Promise<types.DatabaseSessionInfo> {
  return invoke('get_database_session');
}


export async function createDatabase(params: types.CreateDatabaseParams): Promise<string> {
  return invoke('create_database', params);
}


export async function openDatabase(params: types.OpenDatabaseParams): Promise<string> {
  return invoke('open_database', params);
}



export async function closeDatabase(): Promise<void> {
  return invoke('close_database');
}



export async function loadProfile(): Promise<types.AppUserProfile | null> {
  return invoke('load_profile');
}


export async function saveProfile(params: types.SaveProfileParams): Promise<void> {
  return invoke('save_profile', params);
}



export async function clearProfile(): Promise<void> {
  return invoke('clear_profile');
}


export async function storeCredential(params: types.StoreCredentialParams): Promise<void> {
  return invoke('store_credential', params);
}


export async function deleteCredential(params: types.DeleteCredentialParams): Promise<void> {
  return invoke('delete_credential', params);
}


export async function hasCredential(params: types.HasCredentialParams): Promise<boolean> {
  return invoke('has_credential', params);
}



export async function listCredentials(): Promise<types.CredentialInfo[]> {
  return invoke('list_credentials');
}


export async function getCredentialPreview(params: types.GetCredentialPreviewParams): Promise<string> {
  return invoke('get_credential_preview', params);
}


export async function createProfile(params: types.CreateProfileParams): Promise<types.UserProfile> {
  return invoke('create_profile', params);
}


export async function getProfile(params: types.GetProfileParams): Promise<types.UserProfile | null> {
  return invoke('get_profile', params);
}



export async function listProfiles(): Promise<types.UserProfile[]> {
  return invoke('list_profiles');
}


export async function updateProfile(params: types.UpdateProfileParams): Promise<types.UserProfile> {
  return invoke('update_profile', params);
}


export async function deleteProfile(params: types.DeleteProfileParams): Promise<boolean> {
  return invoke('delete_profile', params);
}


export async function greet(params: types.GreetParams): Promise<string> {
  return invoke('greet', params);
}


export async function searchFoodOnline(params: types.SearchFoodOnlineParams): Promise<types.SearchResult> {
  return invoke('search_food_online', params);
}


export async function fetchFoodByBarcode(params: types.FetchFoodByBarcodeParams): Promise<types.SearchResult> {
  return invoke('fetch_food_by_barcode', params);
}


export async function getAiAdvice(params: types.GetAiAdviceParams): Promise<types.AiResponse> {
  return invoke('get_ai_advice', params);
}


