/**
 * Auto-generated TypeScript bindings for Tauri commands
 * Generated by tauri-typegen v0.5.0
 * Generated at: 2026-04-08T22:20:36.393516+00:00
 * Generator: none
 *
 * Do not edit manually - regenerate using: cargo tauri-typegen generate
 */



export interface AiResponse {
  nlogData: string;
  advice: string;
  tokenCount: number;
  provider: string;
}

export interface CredentialInfo {
  service: string;
  hasKey: boolean;
  preview: string;
}


export type MetricUnit = "SERVING" | "GRAM" | "KILOGRAM" | "MILLILITER" | "LITER" | "OUNCE" | "POUND" | "FLUIDOUNCE" | "PINT" | "QUART" | "GALLON" | "TABLESPOON" | "CUP" | "PACKAGE" | "BOX" | "BAG" | "BOTTLE" | "CAN" | "JAR";


export type MealType = "BREAKFAST" | "BRUNCH" | "LUNCH" | "DINNER" | "NIGHTSNACK" | "SNACK" | "CUSTOM";

export interface NetworkConfig {
  networkEnabled: boolean;
  openfoodfactsEnabled: boolean;
  aiFeaturesEnabled: boolean;
}

export interface ChatMessage {
  role: string;
  content: string;
}

export interface Meal {
  id: number;
  occurredAt: number;
  mealType: MealType;
  title: string;
  note: string;
  createdAt: number;
  updatedAt: number;
}

export interface MealItem {
  id: number;
  meal: Meal;
  food: Food;
  serving: Serving;
  quantity: number;
  note: string;
  createdAt: number;
  updatedAt: number;
}

export interface DatabaseSessionInfo {
  connectedPath?: string | null;
  lastPath?: string | null;
  defaultDatabaseDirectory: string;
}

export interface Food {
  id: number;
  name: string;
  brand: string;
  category: string;
  source: string;
  refUrl: string;
  barcode: string;
  createdAt: number;
  updatedAt: number;
}

export interface AppUserProfile {
  version: number;
  createdAt: string;
  updatedAt: string;
  name?: string | null;
  sex: string;
  age: number;
  heightCm: number;
  weightKg: number;
  activityLevel: string;
}


export type Sex = "FEMALE" | "MALE";

export interface SearchProduct {
  productName: string;
  barcode: string;
  brands: string;
  categories: string;
  imageUrl: string;
  caloriesKcal: number;
  fatG: number;
  saturatedFatG: number;
  transFatG: number;
  cholesterolMg: number;
  sodiumMg: number;
  totalCarbohydrateG: number;
  dietaryFiberG: number;
  totalSugarsG: number;
  addedSugarsG: number;
  proteinG: number;
  vitaminDMcg: number;
  calciumMg: number;
  ironMg: number;
}

export interface SearchResult {
  count: number;
  page: number;
  pageSize: number;
  products: SearchProduct[];
}

export interface UserProfile {
  id: number;
  name: string;
  sex: Sex;
  weight: number;
  height: number;
}

export interface Serving {
  id: number;
  food: Food;
  amount: number;
  unit: MetricUnit;
  gramsEquiv: number;
  isDefault: boolean;
  createdAt: number;
  updatedAt: number;
}

export interface NutritionFacts {
  SERVING: Serving;
  CALORIES_KCAL: number;
  FAT_G: number;
  SATURATED_FAT_G: number;
  TRANS_FAT_G: number;
  CHOLESTEROL_MG: number;
  SODIUM_MG: number;
  TOTAL_CARBOHYDRATE_G: number;
  DIETARY_FIBER_G: number;
  TOTAL_SUGARS_G: number;
  ADDED_SUGARS_G: number;
  PROTEIN_G: number;
  VITAMIN_D_MCG: number;
  CALCIUM_MG: number;
  IRON_MG: number;
}

export interface CreateMealParams {
  meal: Meal;
  [key: string]: unknown;
}


export interface GetMealParams {
  id: number;
  [key: string]: unknown;
}



export interface UpdateMealParams {
  meal: Meal;
  [key: string]: unknown;
}


export interface DeleteMealParams {
  id: number;
  [key: string]: unknown;
}


export interface CreateMealItemParams {
  mealItem: MealItem;
  [key: string]: unknown;
}


export interface GetMealItemParams {
  id: number;
  [key: string]: unknown;
}


export interface ListMealItemsByMealParams {
  mealId: number;
  [key: string]: unknown;
}


export interface UpdateMealItemParams {
  mealItem: MealItem;
  [key: string]: unknown;
}


export interface DeleteMealItemParams {
  id: number;
  [key: string]: unknown;
}


export interface ListMealsByDateRangeParams {
  start: number;
  end: number;
  [key: string]: unknown;
}


export interface BuildNlogParams {
  days: number;
  offsetMinutes: number;
  [key: string]: unknown;
}


export interface CreateFoodParams {
  food: Food;
  [key: string]: unknown;
}


export interface GetFoodParams {
  id: number;
  [key: string]: unknown;
}



export interface UpdateFoodParams {
  food: Food;
  [key: string]: unknown;
}


export interface DeleteFoodParams {
  id: number;
  [key: string]: unknown;
}


export interface CreateServingParams {
  serving: Serving;
  [key: string]: unknown;
}


export interface GetServingParams {
  id: number;
  [key: string]: unknown;
}


export interface ListServingsByFoodParams {
  foodId: number;
  [key: string]: unknown;
}


export interface UpdateServingParams {
  serving: Serving;
  [key: string]: unknown;
}


export interface DeleteServingParams {
  id: number;
  [key: string]: unknown;
}


export interface CreateNutritionFactsParams {
  nutritionFacts: NutritionFacts;
  [key: string]: unknown;
}


export interface GetNutritionFactsParams {
  servingId: number;
  [key: string]: unknown;
}



export interface UpdateNutritionFactsParams {
  nutritionFacts: NutritionFacts;
  [key: string]: unknown;
}


export interface DeleteNutritionFactsParams {
  servingId: number;
  [key: string]: unknown;
}





export interface CreateDatabaseParams {
  path: string;
  [key: string]: unknown;
}


export interface OpenDatabaseParams {
  path: string;
  [key: string]: unknown;
}




export interface SaveProfileParams {
  profile: AppUserProfile;
  [key: string]: unknown;
}



export interface StoreCredentialParams {
  service: string;
  key: string;
  [key: string]: unknown;
}


export interface DeleteCredentialParams {
  service: string;
  [key: string]: unknown;
}


export interface HasCredentialParams {
  service: string;
  [key: string]: unknown;
}



export interface GetCredentialPreviewParams {
  service: string;
  [key: string]: unknown;
}


export interface CreateProfileParams {
  userProfile: UserProfile;
  [key: string]: unknown;
}


export interface GetProfileParams {
  id: number;
  [key: string]: unknown;
}



export interface UpdateProfileParams {
  userProfile: UserProfile;
  [key: string]: unknown;
}


export interface DeleteProfileParams {
  id: number;
  [key: string]: unknown;
}


export interface GreetParams {
  name: string;
  [key: string]: unknown;
}


export interface SearchFoodOnlineParams {
  query: string;
  page: number;
  [key: string]: unknown;
}


export interface FetchFoodByBarcodeParams {
  barcode: string;
  [key: string]: unknown;
}


export interface GetAiAdviceParams {
  question: string;
  days: number;
  provider?: string | null;
  history?: ChatMessage[] | null;
  offsetMinutes?: number | null;
  [key: string]: unknown;
}


