name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install frontend deps
      run: npm install

    - name: Build frontend
      run: npm run build

    - name: Build Tauri
      run: cargo build --release

    - name: Run Rust tests
      run: cargo test
